---
title: "Data Management"
output: github_document
---

```{r setup, include = FALSE}

pacman::p_load(
  rio,        # importing data  
  here,       # relative file pathways  
  janitor,    # data cleaning and tables
  lubridate,  # working with dates
  epikit,     # age_categories() function
  tidyverse   # data management and visualization
)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

## Load Linelist

```{r}
linelist_raw <- import("./data/linelist_raw.xlsx") 

linelist <- linelist_raw %>%
  janitor::clean_names() %>%
  rename(
    date_infection = infection_date,
    date_hospitalization = hosp_date,
    date_outcome = date_of_outcome
  )

#Review
skimr::skim(linelist_raw)

#Look at column names
names(linelist_raw)

#Can reference column name with spaces using back-ticks ex: linelist$`x60\infection date\x60`
```


Manipulate Columns

```{r}
# select
linelist %>%
  select(case_id, date_onset, date_hospitalization, fever) %>%
  names()

# everything- move onset and hospitaliation to front
linelist %>%
  select(date_onset, date_hospitalization, everything()) %>%
  names()

# select columns that are class numeric
linelist %>%
  select(where(is.numeric)) %>%
  names()

# select columns containing certain characters
linelist %>%
  select(contains("date")) %>%
  names()

# searched for multiple character matches- needs to be exact or will generate an error
linelist %>%
  select(matches("onset|hosp|fev")) %>%
  names()

# consider using any_of to search for columns that may or may not exist
linelist %>%
  select(any_of(c("date_onset","village_origin","village_detection","village_residence","village_travel"))) %>%
  names()

# remove columns
linelist %>%
  select(-c(date_onset, fever:vomit)) %>%
  names()


# create new linelist with id and age-realted columns
linelist_age <- select(linelist, case_id, contains("age"))

names(linelist_age)

```


Addition to pipe chain

```{r}
linelist <- linelist_raw %>%
  janitor::clean_names() %>%
  rename(date_infection       = infection_date,
           date_hospitalisation = hosp_date,
           date_outcome         = date_of_outcome) %>%
  select(-c(row_num, merged_header, x28)) %>%
  distinct()
```

New Columns

```{r}
new_col_demo <- linelist %>%                       
  mutate(
    new_var_dup    = case_id,             # new column = duplicate/copy another existing column
    new_var_static = 7,                   # new column = all values the same
    new_var_static = new_var_static + 5,  # you can overwrite a column, and it can be a calculation using other variables
    new_var_paste  = stringr::str_glue("{hospital} on ({date_hospitalisation})") # new column = pasting together values from other columns
    ) %>% 
  select(case_id, hospital, date_hospitalisation, contains("new"))        # show only new columns, for demonstration purposes

linelist <- linelist %>%
  select(-contains("new_var"))
```

Grouped Data

```{r}
class(linelist$age)

linelist <- linelist %>%
  mutate(age = as.numeric(age))

# age normalized to mean of all rows
linelist %>%
  mutate(age_norm = age / mean(age, na.rm = T))

# age normalized to mean of hospital group
linelist %>%
  group_by(hospital) %>%
  mutate(age_norm = age / mean(age, na.rm = T))
```


Transform multiple columns

across()

```{r}
# specify argument .cols = and the function(s) to apply to .fns

# as.character applied to specific columns named within across()
linelist <- linelist %>%
  mutate(across(.cols = c(temp, ht_cm, wt_kg), .fns = as.character))

# change all columns to character class
linelist <- linelist %>%
  mutate(across(.cols = everything(), .fns = as.character))
         
# to change all columns to character class
linelist <- linelist %>%
  mutate(across(.cols = contains("date"), .fns = as.character))

# apply date function to posixct objects
linelist <- linelist %>%
  mutate(across(.cols = where(is.POSIXct), .fns = as.Date))
```


coalesce()

```{r}
village_detection <- c("a","b",NA, NA)
village_residence <- c("a","b","a","d")

village <- coalesce(village_detection, village_residence)
village

```

cumulative math

```{r}
cumsum(c(2,4,15,10))

cumulative_case_counts <- linelist %>%
  count(date_onset) %>%
  mutate(cumulative_cases = cumsum(n))

head(cumulative_case_counts, 10)
```


add to pipe chain

```{r}
linelist <- linelist_raw %>%
    
    janitor::clean_names() %>% 

    rename(date_infection       = infection_date,
           date_hospitalisation = hosp_date,
           date_outcome         = date_of_outcome) %>% 
    
    select(-c(row_num, merged_header, x28)) %>% 
    distinct() %>% 
  
    mutate(bmi = wt_kg / (ht_cm/100)^2) %>% 
  
    mutate(across(contains("date"), as.Date), 
           generation = as.numeric(generation),
           age        = as.numeric(age)) 
```

# Re-code values

Specific changes

```{r}
#linelist <- linelist %>% 
  #mutate(date_onset = recode(date_onset, "2014-14-15" = "2014-04-15"))

table(linelist$hospital, useNA = "always")

linelist <- linelist %>%
  mutate(hospital = recode(hospital,
                      "Mitylira Hopital"  = "Military Hospital",
                      "Mitylira Hospital" = "Military Hospital",
                      "Military Hopital"  = "Military Hospital",
                      "Port Hopital"      = "Port Hospital",
                      "Central Hopital"   = "Central Hospital",
                      "other"             = "Other",
                      "St. Marks Maternity Hopital (SMMH)" = "St. Mark's Maternity Hospital (SMMH)"
                      ))
```

By Logic

```{r}
## Simple Logic

# Example: change gender of one specific observation to "Female"

# replace()
linelist <- linelist %>%
  mutate(gender = replace(gender, case_id == "2195","Female"))

# ifelse() and if_else()
linelist <- linelist %>%
  mutate(source_known = ifelse(!is.na(source), "known","unknown"))

# Create a date of death column, which is NA if patient has not died
linelist <- linelist %>%
  mutate(date_death = if_else(outcome == "Death", date_outcome,NA_real_))


## Complex Logic
linelist <- linelist %>%
  mutate(age_years = case_when(
    age_unit == "years"  ~ age,       # if age is given in years
    age_unit == "months" ~ age/12,    # if age is given in months
    is.na(age_unit)      ~ age,       # if age unit is missing
    TRUE                 ~ NA_real_)) # any other circumstance, assign missing
```


Missing Values

```{r}
# replace_na()
linelist <- linelist %>%
  mutate(hospital = replace_na(hospital, "Missing"))

# fct_explicit_na()- deals specifically with factors
linelist %>%
  mutate(hospital = fct_explicit_na(hospital))

# na_if()- convert specific value to NA
linelist <- linelist %>%
  mutate(hospital = na_if(hospital, "Missing"))

# na_if() cannot be used with logical criteria- use replace() or case_when() for this

# Convert temperatures above 40 to NA
linelist <- linelist %>%
  mutate(temp = replace(temp, temp > 40, NA))

# Convert onset dates earlier than 1 Jan 2000 to missing
linelist <- linelist %>%
  mutate(date_onset = replace(date_onset, date_onset > as.Date("2000-01-01"),NA))
```

Cleaning Dictionary

```{r}
cleaning_dict <- import("https://github.com/appliedepi/epirhandbook_eng/raw/master/data/case_linelists/cleaning_dict.csv")

# cleaning_dict <- import("cleaning_dict.csv")- use if file saved locally

linelist <- linelist %>%
  linelist::clean_variable_spelling(
    wordlists = cleaning_dict,
    spelling_vars = "col",       # dict column containing column names, defaults to 3rd column in dict
  )

```


Add to pipe chain

```{r}

linelist <- linelist_raw %>%
    
    # standardize column name syntax
    janitor::clean_names() %>% 
    
    # manually re-name column
  
    rename(date_infection       = infection_date,
           date_hospitalisation = hosp_date,
           date_outcome         = date_of_outcome) %>% 
    
    # remove column
    select(-c(row_num, merged_header, x28)) %>% 
  
    # de-duplicate
    distinct() %>% 
  
    # add column
    mutate(bmi = wt_kg / (ht_cm/100)^2) %>%     

    # convert class of columns
    mutate(across(contains("date"), as.Date), 
           generation = as.numeric(generation),
           age        = as.numeric(age)) %>% 
    
    # add column: delay to hospitalisation
    mutate(days_onset_hosp = as.numeric(date_hospitalisation - date_onset)) %>% 

    # clean values of hospital column
    mutate(hospital = recode(hospital,
                      # OLD = NEW
                      "Mitylira Hopital"  = "Military Hospital",
                      "Mitylira Hospital" = "Military Hospital",
                      "Military Hopital"  = "Military Hospital",
                      "Port Hopital"      = "Port Hospital",
                      "Central Hopital"   = "Central Hospital",
                      "other"             = "Other",
                      "St. Marks Maternity Hopital (SMMH)" = "St. Mark's Maternity Hospital (SMMH)"
                      )) %>% 
    
    mutate(hospital = replace_na(hospital, "Missing")) %>% 

    # create age_years column (from age and age_unit)
    mutate(age_years = case_when(
          age_unit == "years" ~ age,
          age_unit == "months" ~ age/12,
          is.na(age_unit) ~ age,
          TRUE ~ NA_real_))
```


## Numeric Categories

```{r}
# examine distribution of linelist variable age
hist(linelist$age_years)

summary(linelist$age_years, na.rm=T)

# age_categories
pacman::p_load(epikit)                     # load package

linelist <- linelist %>%
  mutate(
    age_cat = age_categories(
      age_years,                           # numeric column to make groups from
      breakers = c(0, 5, 10, 15, 20,       # break points
                   30, 40, 50, 60, 70),
      separator = "-"))                    # separator is "-" by default

# show table
table(linelist$age_cat, useNA = "always")

# With ceiling set to TRUE
##########################
linelist <- linelist %>% 
  mutate(
    age_cat = age_categories(
      age_years, 
      breakers = c(0, 5, 10, 15, 20, 30, 40, 50, 60, 70),
      ceiling = TRUE)) # 70 is ceiling, all above become NA

# show table
table(linelist$age_cat, useNA = "always")

# using lower, upper, and by
linelist <- linelist %>%
  mutate(
    age_cat = age_categories(
      age_years,
      lower = 0,
      upper = 100,
      by = 10))

# show table
table(linelist$age_cat, useNA = "always")
```

cut()

```{r}

```






